const data = [
    {
     category: 'online codes' ,
     title: 'Fusion Strike - Online Codes', 
     price: 0.54, 
     stock: 5, 
     picUrl: '/imgs/FST.png', 
     description: 'Fusion Strike digital code card contains 11 assorted cards that you can use within the Pokemon Trading Card Game Online. These online code cards contain a random assortment of Pokemon, Trainer, and Energy cards. Each pack contains 5 Common Cards, 3 Uncommon Cards, a Reverse Holo Card, a Basic Energy Card, and at least a Rare Card (or higher). In the Sword and Shield block of cards, there are plenty of powerful Pokemon V, VMAX, and Special Art cards to explore. These cards are currently available for play in our Expanded format, Legacy format (some), and are available for play in our current Standard format. Expand your collection by acquiring Fusion Strike online PTCGO code cards today!',
     tags: ['fusion', 'strike', 'online', 'codes', 'fusion strike', 'online codes'],
    },
    {
     category: 'online codes', 
     title: 'Evolving Skies - Online Codes', 
     price: 0.22, 
     stock: 20, 
     picUrl: '/imgs/EVS.png', 
     description: 'Each Evolving Skies digital code card contains 11 assorted cards that you can use within the Pokemon Trading Card Game Online. These online code cards contain a random assortment of Pokemon, Trainer, and Energy cards. Each pack contains 5 Common Cards, 3 Uncommon Cards, a Reverse Holo Card, a Basic Energy Card, and at least a Rare Card (or higher). In the Sword and Shield block of cards, there are plenty of powerful Pokemon V, VMAX, and Special Art cards to explore. These cards are currently available for play in our Expanded format, Legacy format (some), and are available for play in our current Standard format. Expand your collection by acquiring Evolving Skies online PTCGO code cards today!',
     tags: ['evolving', 'skies', 'online', 'codes', 'evolving skies', 'online codes'],
    },
    {
     category: 'online codes', 
     title: 'Brilliant Stars - Online Codes', 
     price: 0.99, 
     stock: 31, 
     picUrl: '/imgs/BRS.png',
     description: 'Each Brilliant Stars digital code card contains 11 assorted cards that you can use within the Pokemon Trading Card Game Online. These online code cards contain a random assortment of Pokemon, Trainer, and Energy cards. Each pack contains 5 Common Cards, 3 Uncommon Cards, a Reverse Holo Card, a Basic Energy Card, and at least a Rare Card (or higher). In the Sword and Shield block of cards, there are plenty of powerful Pokemon V, VMAX, and Special Art cards to explore. These cards are currently available for play in our Expanded format, Legacy format (some), and are available for play in our current Standard format. Expand your collection by acquiring Brilliant Stars online PTCGO code cards today!',
     tags: ['brilliant', 'stars', 'online', 'codes', 'brilliant stars', 'online codes'],
    },
    {
     category: 'online codes', 
     title: 'Battle Styles - Online Codes', 
     price: 0.15, 
     stock: 50, 
     picUrl: '/imgs/BST.png',
     description: 'Each Battle Styles digital code card contains 11 assorted cards that you can use within the Pokemon Trading Card Game Online. These online code cards contain a random assortment of Pokemon, Trainer, and Energy cards. Each pack contains 5 Common Cards, 3 Uncommon Cards, a Reverse Holo Card, a Basic Energy Card, and at least a Rare Card (or higher). In the Sword and Shield block of cards, there are plenty of powerful Pokemon V, VMAX, and Special Art cards to explore. These cards are currently available for play in our Expanded format, Legacy format (some), and are available for play in our current Standard format. Expand your collection by acquiring Battle Styles online PTCGO code cards today!',
     tags: ['battle', 'styles', 'online', 'codes' , 'battle styles', 'online codes'],
    },
    {
     category: 'online codes', 
     title: 'Chilling Reigns - Online Codes', 
     price: 0.18, 
     stock: 20, 
     picUrl: '/imgs/CRE.png',
     description: 'Each Chilling Reigns digital code card contains 11 assorted cards that you can use within the Pokemon Trading Card Game Online. These online code cards contain a random assortment of Pokemon, Trainer, and Energy cards. Each pack contains 5 Common Cards, 3 Uncommon Cards, a Reverse Holo Card, a Basic Energy Card, and at least a Rare Card (or higher). In the Sword and Shield block of cards, there are plenty of powerful Pokemon V, VMAX, and Special Art cards to explore. These cards are currently available for play in our Expanded format, Legacy format (some), and are available for play in our current Standard format. Expand your collection by acquiring Chilling Reigns online PTCGO code cards today!',
     tags: ['chilling', 'reigns', 'online', 'codes', 'chilling reigns', 'online codes'],
    },
    {
     category: 'online codes', 
     title: 'Darkness Ablaze - Online Codes', 
     price: 0.31, 
     stock: 16, 
     picUrl: '/imgs/DAB.png',
     description: 'Each Darkness Ablaze digital code card contains 11 assorted cards that you can use within the Pokemon Trading Card Game Online. These online code cards contain a random assortment of Pokemon, Trainer, and Energy cards. Each pack contains 5 Common Cards, 3 Uncommon Cards, a Reverse Holo Card, a Basic Energy Card, and at least a Rare Card (or higher). In the Sword and Shield block of cards, there are plenty of powerful Pokemon V, VMAX, and Special Art cards to explore. These cards are currently available for play in our Expanded format, Legacy format (some), and are available for play in our current Standard format. Expand your collection by acquiring Darkness Ablaze online PTCGO code cards today!',
     tags: ['darkess', 'ablaze', 'online', 'codes', 'darkness ablaze', 'online codes'],
    },
    {
     category: 'online codes', 
     title: 'Vivid Voltage - Online Codes', 
     price: 0.09, 
     stock: 13, 
     picUrl: '/imgs/VIV.png',
     description: 'Each Vivid Voltage digital code card contains 11 assorted cards that you can use within the Pokemon Trading Card Game Online. These online code cards contain a random assortment of Pokemon, Trainer, and Energy cards. Each pack contains 5 Common Cards, 3 Uncommon Cards, a Reverse Holo Card, a Basic Energy Card, and at least a Rare Card (or higher). In the Sword and Shield block of cards, there are plenty of powerful Pokemon V, VMAX, and Special Art cards to explore. These cards are currently available for play in our Expanded format, Legacy format (some), and are available for play in our current Standard format. Expand your collection by acquiring Vivid Voltage online PTCGO code cards today!',
     tags: ['vivid', 'voltage', 'online', 'codes',  'vivid voltage', 'online codes'],
    },
    {
     category: 'online codes', 
     title: 'Rebel Clash - Online Codes', 
     price: 0.24, 
     stock: 8, 
     picUrl: '/imgs/RCL.png',
     description: 'Each Rebel Clash digital code card contains 11 assorted cards that you can use within the Pokemon Trading Card Game Online. These online code cards contain a random assortment of Pokemon, Trainer, and Energy cards. Each pack contains 5 Common Cards, 3 Uncommon Cards, a Reverse Holo Card, a Basic Energy Card, and at least a Rare Card (or higher). In the Sword and Shield block of cards, there are plenty of powerful Pokemon V, VMAX, and Special Art cards to explore. These cards are currently available for play in our Expanded format, Legacy format (some), and are available for play in our current Standard format. Expand your collection by acquiring Rebel Clash online PTCGO code cards today!',
     tags: ['clash', 'rebel', 'online', 'codes', 'rebel clash', 'online codes'],
    },
    {
     category: 'online codes', 
     title: 'Sword and Shield - Online Codes', 
     price: 0.13, 
     stock: 42, 
     picUrl: '/imgs/SWSH.png',
     description: 'Each Sword And Shield digital code card contains 11 assorted cards that you can use within the Pokemon Trading Card Game Online. These online code cards contain a random assortment of Pokemon, Trainer, and Energy cards. Each pack contains 5 Common Cards, 3 Uncommon Cards, a Reverse Holo Card, a Basic Energy Card, and at least a Rare Card (or higher). In the Sword and Shield block of cards, there are plenty of powerful Pokemon V, VMAX, and Special Art cards to explore. These cards are currently available for play in our Expanded format, Legacy format (some), and are available for play in our current Standard format. Expand your collection by acquiring Sword And Shield online PTCGO code cards today!',
     tags: ['sword', 'shield', 'online', 'codes', 'sword and shield', 'online codes'],
    },
    {
     category: 'sealed products', 
     title: 'Hoopa V Box', 
     price: 18.50, 
     stock: 2, 
     picUrl: '/imgs/HoopaBox.png',
     description: 'Accompanying the Fusion Strike expansion on November 12, 2021 was an array of other sealed products. One of these was the Hoopa V Box, which came packaged with regular and oversized copies of Hoopa V (omitted from Fusion Strike during localization), a code card for the Pokémon Trading Card Game Online, and four booster packs.',
     tags: ['hoopa', 'v', 'box', 'hoopa v', 'hoopa v box'],
    },
    {
     category: 'sealed products', 
     title: 'Fusion Strike Elite Trainer Box', 
     price: 34.99, 
     stock: 1, 
     picUrl: '/imgs/FSTElite.png',
     description: 'The Fusion Strike Elite Trainer Box was released in time with the launch of the Fusion Strike expansion on November 12, 2021. The box design features the Mythical Pokémon Mew and each box came packaged with eight Fusion Strike booster packs, 65 card sleeves and four dividers with a Mew design, six damage counter dice, a coin-flip die, two acrylic Special Condition markers, 45 basic Energy cards, a rulebook, a Fusion Strike Players Guide, and a Pokémon Trading Card Game Live code card. The Pokémon Center-exclusive Fusion Strike Pokémon Center Elite Trainer Box was also available on November 12 and contained largely the same items.',
     tags: ['fusion', 'strike', 'elite', 'etb', 'fusion strike', 'fusion strike etb', 'fusion strike elite trainer box', 'trainer'],
    },
    {
     category: 'sealed products', 
     title: 'Galarian Rapidash V Box', 
     price: 12.99, 
     stock: 1, 
     picUrl: '/imgs/GRapidashV.png',
     description: 'Released May 7, 2021 was the Galarian Rapidash V Box, which included the Unique Horn Pokémon as both standard and Jumbo-sized promotional cards. Each box also came with four booster packs and a code card to unlock Galarian Rapidash V in the Pokémon Trading Card Game Online.',
     tags: ['galarian', 'raídash', 'v', 'box', 'galarian rapidash', 'galarian rapidash v box'],
    },
    {
     category: 'sealed products', 
     title: 'Single Strike Urshifu VMAX Premium Collection', 
     price: 99.99, 
     stock: 4, 
     picUrl: '/imgs/SSPremium.png',
     description: 'The Single Strike Urshifu VMAX Premium Collection was released alongside its Single Strike counterpart on November 12, 2021. Taking inspiration from the Urshifu-centric box available earlier in 2021, it included a copy of Single Strike Urshifu V, standard-sized and Jumbo-sized copies of Single Strike Urshifu VMAX, and a Parallel Holofoil copy of Single Strike Energy. Each collection also came packaged with eight Sword & Shield Series booster packs and a TCGO code card.',
     tags: ['collection', 'premium', 'v', 'vmax', 'urshifu' , 'single strike', 'premium collection', 'single strike urshifu vmax', 'single strike urshifu', 'single strike urshifu vmax premium collection']
    },
    {
     category: 'sealed products', 
     title: 'Single Strike Urshifu VMAX League Battle Deck', 
     price: 24.99, 
     stock: 1, 
     picUrl: '/imgs/SSDeck.png',
     description: 'Urshifu was also the focus of two more League Battle Decks released on November 12, 2021. The Single Strike Urshifu VMAX League Battle Deck centered on the heavy-hitting style of the Wushu Pokémon, featuring multiples of Single Strike Urshifu V and Single Strike Urshifu VMAX in the selection of 60 tournament-tried cards. Each deck also included two condition markers, six damage-counter dice, a competition-legal coin-flip die, a rulebook, a Quick Guide, and a TCGO code card.',
     tags: ['deck', 'battle', 'v', 'vmax', 'urshifu' , 'single strike', 'battle deck', 'league battle deck', 'single strike urshifu', 'single strike urshifu vmax', 'single strike urshifu vmax league battle deck'],
    },
    {
     category: 'sealed products', 
     title: 'Rapid Strike Urshifu VMAX Premium Collection', 
     price: 99.99, 
     stock: 0, 
     picUrl: '/imgs/RSPremium.png',
     description: 'The Rapid Strike Urshifu VMAX Premium Collection was released alongside its Single Strike counterpart on November 12, 2021. Taking inspiration from the Urshifu-centric box available earlier in 2021, it included a copy of Rapid Strike Urshifu V, standard-sized and Jumbo-sized copies of Rapid Strike Urshifu VMAX, and a Parallel Holofoil copy of Rapid Strike Energy. Each collection also came packaged with eight Sword & Shield Series booster packs and a TCGO code card.',
     tags: [ 'collection', 'premium', 'v', 'vmax', 'urshifu' , 'rapid strike', 'premium collection', 'rapid strike urshifu', 'rapid strike urshifu vmax', 'rapid strike urshifu vmax premium collection'],
    },
    {
     category: 'sealed products', 
     title: 'Rapid Strike Urshifu VMAX League Battle Deck', 
     price: 24.99, 
     stock: 2, 
     picUrl: '/imgs/RSDeck.png',
     description: 'Urshifu was also the focus of two more League Battle Decks released on November 12, 2021. The Rapid Strike Urshifu VMAX League Battle Deck centered on the rapid-hitting style of the Wushu Pokémon, featuring multiples of Rapid Strike Urshifu V and Rapid Strike Urshifu VMAX in the selection of 60 tournament-tried cards. Each deck also included two condition markers, six damage-counter dice, a competition-legal coin-flip die, a rulebook, a Quick Guide, and a TCGO code card.',
     tags: ['deck', 'battle', 'v', 'vmax', 'urshifu' , 'rapid strike', 'battle deck', 'league battle deck', 'rapid strike urshifu', 'rapid strike urshifu vmax', 'rapid strike urshifu vmax league battle deck'],
    },
    {
     category: 'sealed products', 
     title: 'Vaporeon VMAX Premium Collection', 
     price: 69.99, 
     stock: 21, 
     picUrl: '/imgs/VaporeonPremium.png',
     description: 'Three Premium Collections were released on December 3, 2021 focusing on the Kanto region Eeveelutions. One of these was the Vaporeon VMAX Premium Collection, which featured the Special Full Art version of Vaporeon V omitted from Evolving Skies during localization and a Special Full Art version of Vaporeon VMAX that originated as a rather limited Japanese promotional card. Two versions of the collection were available: one for sale in North America and another for sale outside North America. Both versions included the two Vaporeon cards, a code card to unlock them in the TCGO, a Jumbo copy of the Vaporeon VMAX, and a Vaporeon pin. The North American version also included six booster packs and an extra-large coin, whereas the International version only included five booster packs and no coin.',
     tags: ['collection', 'premium', 'v', 'vmax', 'vaporeon', 'rapid strike', 'vaporeon v', 'vaporeon vmax', 'vaporeon vmax premium collection', 'premium collection'],
    },
    {
     category: 'sealed products', 
     title: 'Jolteon VMAX Premium Collection', 
     price: 69.99, 
     stock: 2, 
     picUrl: '/imgs/JolteonPremium.png',
     description: 'Three Premium Collections were released on December 3, 2021 focusing on the Kanto region Eeveelutions. One of these was the Vaporeon VMAX Premium Collection, which featured the Special Full Art version of Vaporeon V omitted from Evolving Skies during localization and a Special Full Art version of Vaporeon VMAX that originated as a rather limited Japanese promotional card. Two versions of the collection were available: one for sale in North America and another for sale outside North America. Both versions included the two Vaporeon cards, a code card to unlock them in the TCGO, a Jumbo copy of the Vaporeon VMAX, and a Vaporeon pin. The North American version also included six booster packs and an extra-large coin, whereas the International version only included five booster packs and no coin.',
     tags: ['collection', 'premium', 'v', 'vmax', 'jolteon', 'jolteon v', 'jolteon vmax', 'jolteon vmax premium collection', 'premium collection'],
    },
    {
     category: 'sealed products', 
     title: 'Flareon VMAX Premium Collection', 
     price: 69.99, 
     stock: 10, 
     picUrl: '/imgs/FlareonPremium.png',
     description: 'Three Premium Collections were released on December 3, 2021 focusing on the Kanto region Eeveelutions. One of these was the Vaporeon VMAX Premium Collection, which featured the Special Full Art version of Vaporeon V omitted from Evolving Skies during localization and a Special Full Art version of Vaporeon VMAX that originated as a rather limited Japanese promotional card. Two versions of the collection were available: one for sale in North America and another for sale outside North America. Both versions included the two Vaporeon cards, a code card to unlock them in the TCGO, a Jumbo copy of the Vaporeon VMAX, and a Vaporeon pin. The North American version also included six booster packs and an extra-large coin, whereas the International version only included five booster packs and no coin.',
     tags: ['collection', 'premium', 'v', 'vmax', 'flareon' , 'single strike', 'flareon v', 'flareon vmax', 'flareon vmax premium collection', 'premium collection'],
    },
    {
     category: 'sealed products', 
     title: 'Brilliant Stars Elite Trainer Box', 
     price: 49.99, 
     stock: 3, 
     picUrl: '/imgs/BRSElite.png',
     description: 'The Brilliant Stars Elite Trainer Box was released in time with the launch of the Brilliant Stars expansion on February 2022. The box design features the Mythical Pokémon Arceus and each box came packaged with eight Brilliant Stars booster packs, 65 card sleeves and four dividers with an Arceus design, six damage counter dice, a coin-flip die, two acrylic Special Condition markers, 45 basic Energy cards, a rulebook, a Brilliant Stars Players Guide, and a Pokémon Trading Card Game Live code card. The Pokémon Center-exclusive Brilliant Stars Pokémon Center Elite Trainer Box was also available on February 22 and contained largely the same items.',
     tags: ['brilliant', 'stars', 'elite', 'etb', 'brilliant stars', 'brilliant stars etb', 'brilliant stars elite trainer box', 'trainer', 'brs'],
    },
    {
     category: 'sealed products', 
     title: 'Brilliant Stars Booster Box', 
     price: 89.99, 
     stock: 10, 
     picUrl: '/imgs/BRSBBox.png',
     description: 'Shoot for the galaxy in Pokemon TCGs latest set, Brilliant Stars, that showcases some of the first Pokemon VSTAR to the game! Many fan favorite cards are back, like Ultra Ball [Brilliant Stars], and other cards have been spiritually reprinted, such as Choice Band [Guardians Rising] as Choice Belt [Brilliant Stars]. Arceus VSTAR [Brilliant Stars] adds layers of depth into new and existing archetypes by offering Energy acceleration, damage output, and a VSTAR Ability that can search out anything!',
     tags: ['brilliant', 'stars', 'booster', 'box', 'brilliant stars', 'brilliant stars booster box', 'brs'],
    },
    {
     category: 'singles', 
     title: 'Mew V - FST 113/264', 
     price: 9.20, 
     stock: 2, 
     picUrl: '/imgs/MewV.png',
     description: 'Styles Combine in a New Strategy! The road ahead reveals limitless potential as the new Fusion Strike style emerges to harness the unbound spirit of Pokémon and Trainers alike! Adaptable new Pokémon V like Genesect V, Hoopa V, and Mew VMAX are eager for battle, while Single Strike and Rapid Strike Pokémon loom large as Rillaboom VMAX, Cinderace VMAX, and Inteleon VMAX appear in their Gigantamax forms. Go with the flow and discover powerful new strategies in Pokémon TCG: Sword & Shield—Fusion Strike!',
     tags: ['mew', 'v', 'fst', '113/264', '113', 'mew v'],
    },
    {
     category: 'singles', 
     title: 'Mew VMAX - FST 114/264', 
     price: 39.99, 
     stock: 1, 
     picUrl: '/imgs/MewVmax.png',
     description: 'Styles Combine in a New Strategy! The road ahead reveals limitless potential as the new Fusion Strike style emerges to harness the unbound spirit of Pokémon and Trainers alike! Adaptable new Pokémon V like Genesect V, Hoopa V, and Mew VMAX are eager for battle, while Single Strike and Rapid Strike Pokémon loom large as Rillaboom VMAX, Cinderace VMAX, and Inteleon VMAX appear in their Gigantamax forms. Go with the flow and discover powerful new strategies in Pokémon TCG: Sword & Shield—Fusion Strike!',
     tags: ['mew', 'v', 'vmax', 'fst', '114/264', '114', 'mew vmax', 'mew v'],
    },
    {
     category: 'singles', 
     title: 'Gengar V - FST 156/264', 
     price: 5.50, 
     stock: 4, 
     picUrl: '/imgs/GengarV.png',
     description: 'Styles Combine in a New Strategy! The road ahead reveals limitless potential as the new Fusion Strike style emerges to harness the unbound spirit of Pokémon and Trainers alike! Adaptable new Pokémon V like Genesect V, Hoopa V, and Mew VMAX are eager for battle, while Single Strike and Rapid Strike Pokémon loom large as Rillaboom VMAX, Cinderace VMAX, and Inteleon VMAX appear in their Gigantamax forms. Go with the flow and discover powerful new strategies in Pokémon TCG: Sword & Shield—Fusion Strike!',
     tags: ['gengar', 'v', 'fst', '156/264', '156', 'gengar v'],
    },
    {
     category: 'singles', 
     title: 'Gengar VMAX - FST 157/264', 
     price: 19.92, 
     stock: 3, 
     picUrl: '/imgs/GengarVmax.png',
     description: 'Styles Combine in a New Strategy! The road ahead reveals limitless potential as the new Fusion Strike style emerges to harness the unbound spirit of Pokémon and Trainers alike! Adaptable new Pokémon V like Genesect V, Hoopa V, and Mew VMAX are eager for battle, while Single Strike and Rapid Strike Pokémon loom large as Rillaboom VMAX, Cinderace VMAX, and Inteleon VMAX appear in their Gigantamax forms. Go with the flow and discover powerful new strategies in Pokémon TCG: Sword & Shield—Fusion Strike!',
     tags: ['gengar', 'v','vmax', 'fst', '157/264', '157', 'gengar vmax', 'gengar v'],
    },
    {
     category: 'singles', 
     title: 'Genesect V - FST 185/264', 
     price: 9.80, 
     stock: 5, 
     picUrl: '/imgs/GenesectV.png',
     description: 'Styles Combine in a New Strategy! The road ahead reveals limitless potential as the new Fusion Strike style emerges to harness the unbound spirit of Pokémon and Trainers alike! Adaptable new Pokémon V like Genesect V, Hoopa V, and Mew VMAX are eager for battle, while Single Strike and Rapid Strike Pokémon loom large as Rillaboom VMAX, Cinderace VMAX, and Inteleon VMAX appear in their Gigantamax forms. Go with the flow and discover powerful new strategies in Pokémon TCG: Sword & Shield—Fusion Strike!',
     tags: ['genesect', 'v', 'fst', '185/264', '185', 'genesect v'],
    },
    {
     category: 'singles', 
     title: 'Jolteon VMAX - EVS 051/203', 
     price: 14.50, 
     stock: 3, 
     picUrl: '/imgs/JolteonVmax.png',
     description: 'Dynamic Power on the Horizon! Feel the power of the shifting winds, and brace for an epic storm as mighty Dragon-type Pokémon make their triumphant return! Rayquaza VMAX leads the surge from on high, and Duraludon VMAX towers above the land in its Gigantamax form, joined by Dragonite V, Noivern V, and more. As the clouds part, Eevee Evolutions appear in a full rainbow of Pokémon V and Pokémon VMAX to signal a bright new day in Pokémon TCG: Sword & Shield—Evolving Skies!',
     tags: ['jolteon', 'v', 'vmax', 'evs', '051/203', 'jolteon vmax'],
    },
    {
     category: 'singles', 
     title: 'Leafeon VMAX - EVS 008/203', 
     price: 6.30, 
     stock: 7, 
     picUrl: '/imgs/LeafeonVmax.png',
     description: 'Dynamic Power on the Horizon! Feel the power of the shifting winds, and brace for an epic storm as mighty Dragon-type Pokémon make their triumphant return! Rayquaza VMAX leads the surge from on high, and Duraludon VMAX towers above the land in its Gigantamax form, joined by Dragonite V, Noivern V, and more. As the clouds part, Eevee Evolutions appear in a full rainbow of Pokémon V and Pokémon VMAX to signal a bright new day in Pokémon TCG: Sword & Shield—Evolving Skies!',
     tags: ['leafeon', 'v', 'vmax', 'evs', '008/203', 'leafeon vmax'],
    },
    {
     category: 'singles', 
     title: 'Rayquaza V - EVS 193/203', 
     price: 19.98, 
     stock: 9, 
     picUrl: '/imgs/RayV.png',
     description: 'Dynamic Power on the Horizon! Feel the power of the shifting winds, and brace for an epic storm as mighty Dragon-type Pokémon make their triumphant return! Rayquaza VMAX leads the surge from on high, and Duraludon VMAX towers above the land in its Gigantamax form, joined by Dragonite V, Noivern V, and more. As the clouds part, Eevee Evolutions appear in a full rainbow of Pokémon V and Pokémon VMAX to signal a bright new day in Pokémon TCG: Sword & Shield—Evolving Skies!',
     tags: ['rayquaza', 'v', 'evs', '0193/203', 'rayquaza v'],
    },
    {
     category: 'singles', 
     title: 'Rayquaza VMAX - EVS 111/203', 
     price: 12.00, 
     stock: 5, 
     picUrl: '/imgs/RayVmax.png',
     description: 'Dynamic Power on the Horizon! Feel the power of the shifting winds, and brace for an epic storm as mighty Dragon-type Pokémon make their triumphant return! Rayquaza VMAX leads the surge from on high, and Duraludon VMAX towers above the land in its Gigantamax form, joined by Dragonite V, Noivern V, and more. As the clouds part, Eevee Evolutions appear in a full rainbow of Pokémon V and Pokémon VMAX to signal a bright new day in Pokémon TCG: Sword & Shield—Evolving Skies!',
     tags: ['rayquaza', 'v', 'vmax', 'evs', '111/203', 'rayquaza vmax', 'rayquaza v'],
    },
    {
     category: 'singles', 
     title: 'Suicune V - EVS 031/203', 
     price: 5.95, 
     stock: 10, 
     picUrl: '/imgs/SuicuneV.png',
     description: 'Dynamic Power on the Horizon! Feel the power of the shifting winds, and brace for an epic storm as mighty Dragon-type Pokémon make their triumphant return! Rayquaza VMAX leads the surge from on high, and Duraludon VMAX towers above the land in its Gigantamax form, joined by Dragonite V, Noivern V, and more. As the clouds part, Eevee Evolutions appear in a full rainbow of Pokémon V and Pokémon VMAX to signal a bright new day in Pokémon TCG: Sword & Shield—Evolving Skies!',
     tags: ['suicune', 'v', 'evs', '031/203', 'suicune v'],
    },
    {
     category: 'singles', 
     title: 'Ice Rider Calyrex V - CRE 045/198', 
     price: 2.04, 
     stock: 0, 
     picUrl: '/imgs/IRV.png',
     description: 'Seize the advantage with Pokemon of the frozen lands, with the powerful Ice Rider Calyrex VMAX and Shadow Rider Calyrex VMAX! Discover new ways to play the game with this all new expansion to Sword and Shield and claim total victory in the land of spectral snow.',
     tags: ['ice rider', 'ice', 'rider', 'v', 'cre', '045/198', 'ice rider v'],
    },
    {
     category: 'singles', 
     title: 'Ice Rider Calyrex VMAX - CRE 046/198', 
     price: 9.70, 
     stock: 9, 
     picUrl: '/imgs/IRVmax.png',
     description: 'Seize the advantage with Pokemon of the frozen lands, with the powerful Ice Rider Calyrex VMAX and Shadow Rider Calyrex VMAX! Discover new ways to play the game with this all new expansion to Sword and Shield and claim total victory in the land of spectral snow.',
     tags: ['ice rider', 'ice', 'rider', 'v', 'vmax', 'cre', '046/198', 'ice rider vmax', 'ice rider v'],
    },
    {
     category: 'singles', 
     title: 'Shadow Rider Calyrex V - CRE 074/198', 
     price: 2.90, 
     stock: 6, 
     picUrl: '/imgs/SRV.png',
     description: 'Seize the advantage with Pokemon of the frozen lands, with the powerful Ice Rider Calyrex VMAX and Shadow Rider Calyrex VMAX! Discover new ways to play the game with this all new expansion to Sword and Shield and claim total victory in the land of spectral snow.',
     tags: ['shadow rider', 'shadow', 'rider', 'v', 'cre', '074/198','shadow rider v'],
    },
    {
     category: 'singles', 
     title: 'Shadow Rider Calyrex VMAX - CRE 075/198', 
     price: 9.90, 
     stock: 4, 
     picUrl: '/imgs/SRVmax.png',
     description: 'Seize the advantage with Pokemon of the frozen lands, with the powerful Ice Rider Calyrex VMAX and Shadow Rider Calyrex VMAX! Discover new ways to play the game with this all new expansion to Sword and Shield and claim total victory in the land of spectral snow.',
     tags: ['shadow rider', 'shadow', 'rider', 'v', 'vmax', 'cre', '075/198', 'shadow rider vmax', 'shadow rider v'],
    },
    {
     category: 'singles', 
     title: 'Galarian Moltres V - CRE 097/198', 
     price: 3.20, 
     stock: 4, 
     picUrl: '/imgs/GMoltresV.png',
     description: 'Seize the advantage with Pokemon of the frozen lands, with the powerful Ice Rider Calyrex VMAX and Shadow Rider Calyrex VMAX! Discover new ways to play the game with this all new expansion to Sword and Shield and claim total victory in the land of spectral snow.',
     tags: ['galarian moltres', 'galarian', 'moltres', 'v', 'cre', '097/198', 'galarian moltres v'],
    },
    {
     category: 'singles', 
     title: 'Victini V - BST 021/163', 
     price: 2.65, 
     stock: 20, 
     picUrl: '/imgs/VictiniV.png',
     description: 'Be a titan full of power, or strike with impossible speed! Use the strength of new Pokémon V and Pokémon VMAX to make your way to the top! Discover new ways to play the game with this all new expansion to Sword and Shield.',
     tags: ['victini', 'v', 'bst', '021/163', 'victini v'],
    },
    {
     category: 'singles', 
     title: 'Single Strike Urshifu V - BST 085/163', 
     price: 1.90, 
     stock: 1, 
     picUrl: '/imgs/SSV.png',
     description: 'Be a titan full of power, or strike with impossible speed! Use the strength of new Pokémon V and Pokémon VMAX to make your way to the top! Discover new ways to play the game with this all new expansion to Sword and Shield.',
     tags: ['single strike', 'single', 'strike', 'urshifu', 'v', 'bst', '085/163', 'single strike urshifu v', 'urshifu v']
    },
    {
     category: 'singles', 
     title: 'Single Strike Urshifu VMAX - BST 086/163', 
     price: 3.90, 
     stock: 4, 
     picUrl: '/imgs/SSVmax.png',
     description: 'Be a titan full of power, or strike with impossible speed! Use the strength of new Pokémon V and Pokémon VMAX to make your way to the top! Discover new ways to play the game with this all new expansion to Sword and Shield.',
     tags: ['single strike', 'single', 'strike', 'urhisfu', 'v', 'vmax', 'bst', '086/163', 'single strike urshifu v', 'single strike urshifu vmax', 'urshifu v']
    },
    {
     category: 'singles', 
     title: 'Rapid Strike Urshifu V - BST 087/163', 
     price: 2.99, 
     stock: 9, 
     picUrl: '/imgs/RSV.png',
     description: 'Be a titan full of power, or strike with impossible speed! Use the strength of new Pokémon V and Pokémon VMAX to make your way to the top! Discover new ways to play the game with this all new expansion to Sword and Shield.',
     tags: ['rapid strike', 'rapid', 'strike', 'urhisfu', 'v', 'bst', '087/163', 'rapid strike urshifu v', 'urshifu v']
    },
    {
     category: 'singles', 
     title: 'Rapid Strike Urshifu VMAX - BST 088/163', 
     price: 3.95, 
     stock: 16, 
     picUrl: '/imgs/RSVmax.png',
     description: 'Be a titan full of power, or strike with impossible speed! Use the strength of new Pokémon V and Pokémon VMAX to make your way to the top! Discover new ways to play the game with this all new expansion to Sword and Shield.',
     tags: ['rapid strike', 'rapid', 'strike', 'urhisfu', 'v', 'vmax', 'bst', '088/163', 'rapid strike urshifu v', 'rapid strike urshifu vmax', 'urshifu v']
    },
    {
     category: 'singles', 
     title: 'Arceus V - BRS 123/172', 
     price: 23.99, 
     stock: 1, 
     picUrl: '/imgs/ArceusV.png',
     description: 'Shoot for the galaxy in Pokemon TCGs latest set, Brilliant Stars, that showcases some of the first Pokemon VSTAR to the game! Many fan favorite cards are back, like Ultra Ball [Brilliant Stars], and other cards have been spiritually reprinted, such as Choice Band [Guardians Rising] as Choice Belt [Brilliant Stars]. Arceus VSTAR [Brilliant Stars] adds layers of depth into new and existing archetypes by offering Energy acceleration, damage output, and a VSTAR Ability that can search out anything!',
     tags: ['arceus', 'v', 'brs', '123/172', 'arceus v'],
    },
    {
     category: 'singles', 
     title: 'Arceus VSTAR - BRS 124/172', 
     price: 72.99, 
     stock: 1, 
     picUrl: '/imgs/ArceusVSTAR.png',
     description: 'Shoot for the galaxy in Pokemon TCGs latest set, Brilliant Stars, that showcases some of the first Pokemon VSTAR to the game! Many fan favorite cards are back, like Ultra Ball [Brilliant Stars], and other cards have been spiritually reprinted, such as Choice Band [Guardians Rising] as Choice Belt [Brilliant Stars]. Arceus VSTAR [Brilliant Stars] adds layers of depth into new and existing archetypes by offering Energy acceleration, damage output, and a VSTAR Ability that can search out anything!',
     tags: ['arceus', 'v', 'vstar', 'star', 'brs', '123/172', 'arceus vstar', 'arceus v'],
    },
    {
     category: 'singles', 
     title: 'Charizard VSTAR - BRS 018/172', 
     price: 54.99, 
     stock: 4, 
     picUrl: '/imgs/CharizardVSTAR.png',
     description: 'Shoot for the galaxy in Pokemon TCGs latest set, Brilliant Stars, that showcases some of the first Pokemon VSTAR to the game! Many fan favorite cards are back, like Ultra Ball [Brilliant Stars], and other cards have been spiritually reprinted, such as Choice Band [Guardians Rising] as Choice Belt [Brilliant Stars]. Arceus VSTAR [Brilliant Stars] adds layers of depth into new and existing archetypes by offering Energy acceleration, damage output, and a VSTAR Ability that can search out anything!',
     tags: ['charizard', 'v', 'vstar', 'star', 'brs', '018/172', 'charizard v' , 'charizard vstar'],
    },
    {
     category: 'singles', 
     title: 'Charizard V - BRS 017/172', 
     price: 19.99, 
     stock: 8, 
     picUrl: '/imgs/CharizardV.png',
     description: 'Shoot for the galaxy in Pokemon TCGs latest set, Brilliant Stars, that showcases some of the first Pokemon VSTAR to the game! Many fan favorite cards are back, like Ultra Ball [Brilliant Stars], and other cards have been spiritually reprinted, such as Choice Band [Guardians Rising] as Choice Belt [Brilliant Stars]. Arceus VSTAR [Brilliant Stars] adds layers of depth into new and existing archetypes by offering Energy acceleration, damage output, and a VSTAR Ability that can search out anything!',
     tags: ['charizard', 'v', 'brs', '017/172', 'charizard v'],
    },
    {
     category: 'singles', 
     title: 'Entei V - BRS 022/172', 
     price: 5.99, 
     stock: 4, 
     picUrl: '/imgs/EnteiV.png',
     description: 'Shoot for the galaxy in Pokemon TCGs latest set, Brilliant Stars, that showcases some of the first Pokemon VSTAR to the game! Many fan favorite cards are back, like Ultra Ball [Brilliant Stars], and other cards have been spiritually reprinted, such as Choice Band [Guardians Rising] as Choice Belt [Brilliant Stars]. Arceus VSTAR [Brilliant Stars] adds layers of depth into new and existing archetypes by offering Energy acceleration, damage output, and a VSTAR Ability that can search out anything!',
     tags: ['entei', 'v', 'brs', '022/172', 'entei v'],
    },
];

export default data